const orders = [{
    ID: 1,
    Region: 'Арктическая Якутия',
    PhysicalGeographicalArea: 'Прибрежная часть Хараулахского хребта',
    Well: 'Тикси-30',
    ObservationPeriod: '1992-2017, 2020-2021',
    GeographicalCoordinates: '71.351266, 128.463738',
    Altitude: '50',
    WellDepth: '30',
    STSrange: '-8,9...-12,0',
    GroundTemperature: '-10,7 (30)',
    RockTemperature: '',
    MeasuredDepth: '',
    STSpower: '1,2',
    SoilCompositionSTS: 'Глыбы, щебень, дресва',
    SoilCompositionMMP: 'Аргиллиты трещиноватые и плотные (менее 5%)',
    MesoreliefElement: 'Привершинная поверхность невысокой горной гряды',
    VegetationCover: 'Горная дриадово-лишайниковая тундра',
    GroundCover: 'Осутствует',
    SnowCoverRange: '0-10',
    PermafrostSpecialist: 'ЛКЛ (П.Я.Константинов)',
}, {
    ID: 2,
    Region: 'Северная Якутия',
    PhysicalGeographicalArea: 'Приленская часть Среднесибирского плоскогорья',
    Well: 'Жиганск-15',
    ObservationPeriod: '2015-2021',
    GeographicalCoordinates: '66.465074, 123.215512',
    Altitude: '60',
    WellDepth: '15',
    STSrange: '-2,2...-2,6',
    GroundTemperature: '-2,1 (15)',
    RockTemperature: '',
    MeasuredDepth: '',
    STSpower: '1,0',
    SoilCompositionSTS: 'Пески пылеватые',
    SoilCompositionMMP: 'Пески, глины, выветрелые алевролиты (10%)',
    MesoreliefElement: 'Выположенный участок денудационной равнины',
    VegetationCover: 'Северотаежный лиственничный лес кустарничково-моховый',
    GroundCover: 'Зеленые мхи (10 см)',
    SnowCoverRange: '30-50',
    PermafrostSpecialist: 'ЛКЛ (П.Я.Константинов)',
}, {
    ID: 3,
    Region: 'Центральная Якутия',
    PhysicalGeographicalArea: 'Приленское плато',
    Well: '138',
    ObservationPeriod: '1982-1983, 1995-2021',
    GeographicalCoordinates: '61.25444, 128.50571',
    Altitude: '187',
    WellDepth: '20',
    STSrange: '-0,7...-2,9',
    GroundTemperature: '-2,8 (15)',
    RockTemperature: '',
    MeasuredDepth: '',
    STSpower: '1,2',
    SoilCompositionSTS: 'Пылеватые суглинки',
    SoilCompositionMMP: 'Пылеватые суглинки, супеси, пески (50%)',
    MesoreliefElement: 'Выположенный участок денудационно-аккумулятивной равнины',
    VegetationCover: 'Лиственничный лес разнотравно-брусничный',
    GroundCover: 'Лесная подстилка (5 см)',
    SnowCoverRange: '25-50',
    PermafrostSpecialist: 'ЛКЛ (П.Я.Константинов)',
}, {
    ID: 4,
    Region: 'Центральная Якутия',
    PhysicalGeographicalArea: 'Приленское плато',
    Well: '133',
    ObservationPeriod: '1982-1983, 1995-2021',
    GeographicalCoordinates: '61.25535, 128.49219',
    Altitude: '190',
    WellDepth: '20',
    STSrange: '',
    GroundTemperature: '-2,3 (15)',
    RockTemperature: '',
    MeasuredDepth: '',
    STSpower: '1,3',
    SoilCompositionSTS: 'Пылеватые суглинки',
    SoilCompositionMMP: 'Пылеватые суглинки, супеси, пески (50%)',
    MesoreliefElement: 'Выположенный участок денудационно-аккумулятивной равнины',
    VegetationCover: 'Березово-лиственничный лес разнотравно-брусничный',
    GroundCover: 'Лесная подстилка (5 см)',
    SnowCoverRange: '25-50',
    PermafrostSpecialist: 'ЛКЛ (П.Я.Константинов)',
}, {
    ID: 5,
    Region: 'Центральная Якутия',
    PhysicalGeographicalArea: 'Приленское плато',
    Well: '134',
    ObservationPeriod: '1982-1983, 1995-2021',
    GeographicalCoordinates: '61.25539, 128.50549',
    Altitude: '191',
    WellDepth: '20',
    STSrange: '',
    GroundTemperature: '-2,6 (15)',
    RockTemperature: '',
    MeasuredDepth: '',
    STSpower: '1,3',
    SoilCompositionSTS: 'Пылеватые суглинки',
    SoilCompositionMMP: 'Пылеватые суглинки, супеси, пески (50%)',
    MesoreliefElement: 'Выположенный участок денудационно-аккумулятивной равнины',
    VegetationCover: 'Березово-лиственничный лес разнотравно-брусничный',
    GroundCover: 'Лесная подстилка (5 см)',
    SnowCoverRange: '25-50',
    PermafrostSpecialist: 'ЛКЛ (П.Я.Константинов)',
}, {
    ID: 6,
    Region: 'Центральная Якутия',
    PhysicalGeographicalArea: 'Приленское плато',
    Well: '140',
    ObservationPeriod: '1982-1983, 1995-2021',
    GeographicalCoordinates: '61.25430, 128.50370',
    Altitude: '192',
    WellDepth: '20',
    STSrange: '',
    GroundTemperature: '-2,5 (15)',
    RockTemperature: '',
    MeasuredDepth: '',
    STSpower: '1,3',
    SoilCompositionSTS: 'Пылеватые суглинки',
    SoilCompositionMMP: 'Пылеватые суглинки, супеси, пески (50%)',
    MesoreliefElement: 'Выположенный участок денудационно-аккумулятивной равнины',
    VegetationCover: 'Березово-лиственничный лес разнотравно-брусничный',
    GroundCover: 'Лесная подстилка (5 см)',
    SnowCoverRange: '25-50',
    PermafrostSpecialist: 'ЛКЛ (П.Я.Константинов)',
}, {
    ID: 7,
    Region: 'Центральная Якутия',
    PhysicalGeographicalArea: 'Приленское плато',
    Well: '139',
    ObservationPeriod: '1982-1983, 1995-2021',
    GeographicalCoordinates: '61.25421, 128.50526',
    Altitude: '189',
    WellDepth: '20',
    STSrange: '',
    GroundTemperature: '-2,6 (15)',
    RockTemperature: '',
    MeasuredDepth: '',
    STSpower: '1,1',
    SoilCompositionSTS: 'Пылеватые суглинки',
    SoilCompositionMMP: 'Пылеватые суглинки, супеси, пески (50%)',
    MesoreliefElement: 'Выположенный участок денудационно-аккумулятивной равнины',
    VegetationCover: 'Березово-лиственничный лес разнотравно-брусничный',
    GroundCover: 'Лесная подстилка (5 см)',
    SnowCoverRange: '25-50',
    PermafrostSpecialist: 'ЛКЛ (П.Я.Константинов)',
}, {
    ID: 8,
    Region: 'Центральная Якутия',
    PhysicalGeographicalArea: 'Приленское плато',
    Well: '136',
    ObservationPeriod: '1982-1983, 1995-2021',
    GeographicalCoordinates: '61.25468, 128.51253',
    Altitude: '177',
    WellDepth: '20',
    STSrange: '',
    GroundTemperature: '-2,8 (15)',
    RockTemperature: '',
    MeasuredDepth: '',
    STSpower: '1,2',
    SoilCompositionSTS: 'Пылеватые суглинки',
    SoilCompositionMMP: 'Пылеватые суглинки, супеси, пески (50%)',
    MesoreliefElement: 'Выположенный участок денудационно-аккумулятивной равнины',
    VegetationCover: 'Лиственнично-березовый лес разнотравно-брусничный',
    GroundCover: 'Лесная подстилка (5 см)',
    SnowCoverRange: '25-50',
    PermafrostSpecialist: 'ЛКЛ (П.Я.Константинов)',
}, {
    ID: 9,
    Region: 'Центральная Якутия',
    PhysicalGeographicalArea: 'Приленское плато',
    Well: '137',
    ObservationPeriod: '1982-1983, 1995-2021',
    GeographicalCoordinates: '61.25442, 128.51209',
    Altitude: '181',
    WellDepth: '20',
    STSrange: '',
    GroundTemperature: '-2,7 (15',
    RockTemperature: '',
    MeasuredDepth: '',
    STSpower: '1,2',
    SoilCompositionSTS: 'Пылеватые суглинки',
    SoilCompositionMMP: 'Пылеватые суглинки, супеси, пески (50%)',
    MesoreliefElement: 'Выположенный участок денудационно-аккумулятивной равнины',
    VegetationCover: 'Лиственнично-березовый лес разнотравно-брусничный',
    GroundCover: 'Лесная подстилка (5 см)',
    SnowCoverRange: '25-50',
    PermafrostSpecialist: 'ЛКЛ (П.Я.Константинов)',
}, {
    ID: 10,
    Region: 'Центральная Якутия',
    PhysicalGeographicalArea: 'Приленское плато',
    Well: '141',
    ObservationPeriod: '1982-1983, 1995-2021',
    GeographicalCoordinates: '61.25294, 128.51027',
    Altitude: '178',
    WellDepth: '20',
    STSrange: '',
    GroundTemperature: '-2,5 (15)',
    RockTemperature: '',
    MeasuredDepth: '',
    STSpower: '1,2',
    SoilCompositionSTS: 'Пылеватые суглинки',
    SoilCompositionMMP: 'Пылеватые суглинки, супеси, пески (50%)',
    MesoreliefElement: 'Выположенный участок денудационно-аккумулятивной равнины',
    VegetationCover: 'Березово-лиственничный лес разнотравно-брусничный',
    GroundCover: 'Лесная подстилка (5 см)',
    SnowCoverRange: '25-50',
    PermafrostSpecialist: 'ЛКЛ (П.Я.Константинов)',
}, {
    ID: 11,
    Region: 'Центральная Якутия',
    PhysicalGeographicalArea: 'Приленское плато',
    Well: '142',
    ObservationPeriod: '1982-1983, 1995-2021',
    GeographicalCoordinates: '61.25280, 128.50460',
    Altitude: '177',
    WellDepth: '20',
    STSrange: '',
    GroundTemperature: '-2,6 (15)',
    RockTemperature: '',
    MeasuredDepth: '',
    STSpower: '1,2',
    SoilCompositionSTS: 'Пылеватые суглинки',
    SoilCompositionMMP: 'Пылеватые суглинки, супеси, пески (50%)',
    MesoreliefElement: 'Выположенный участок денудационно-аккумулятивной равнины',
    VegetationCover: 'Березово-лиственничный лес разнотравно-брусничный',
    GroundCover: 'Лесная подстилка (5 см)',
    SnowCoverRange: '25-50',
    PermafrostSpecialist: 'ЛКЛ (П.Я.Константинов)',
}, {
    ID: 12,
    Region: 'Центральная Якутия',
    PhysicalGeographicalArea: 'Приленское плато',
    Well: '1a',
    ObservationPeriod: '1982-1983, 1995-2021',
    GeographicalCoordinates: '61.25152, 128.50360',
    Altitude: '176',
    WellDepth: '20',
    STSrange: '',
    GroundTemperature: '-2,2 (15)',
    RockTemperature: '',
    MeasuredDepth: '',
    STSpower: '1,8',
    SoilCompositionSTS: 'Пылеватые суглинки',
    SoilCompositionMMP: 'Пылеватые суглинки, супеси, пески (50%)',
    MesoreliefElement: 'Выположенный участок денудационно-аккумулятивной равнины',
    VegetationCover: 'Луг на заброшенной пашне',
    GroundCover: 'Травянистая дернина (2 см)',
    SnowCoverRange: '25-50',
    PermafrostSpecialist: 'ЛКЛ (П.Я.Константинов)',
}, {
    ID: 13,
    Region: 'Центральная Якутия',
    PhysicalGeographicalArea: 'Приленское плато',
    Well: '201',
    ObservationPeriod: '1997-2009',
    GeographicalCoordinates: '62.18527, 129.30021',
    Altitude: '221',
    WellDepth: '20',
    STSrange: '-1,1...-3,9',
    GroundTemperature: '-2,7 (15)',
    RockTemperature: '',
    MeasuredDepth: '',
    STSpower: '1,1',
    SoilCompositionSTS: 'Пылеватые суглинки',
    SoilCompositionMMP: 'Пылеватые суглинки, супеси, алевролиты, песчаники (30%)',
    MesoreliefElement: 'Выположенный участок денудационно-аккумулятивной равнины',
    VegetationCover: 'Лиственничный лес разнотравно-брусничный',
    GroundCover: 'Лесная подстилка (7 см)',
    SnowCoverRange: '25-55',
    PermafrostSpecialist: 'ЛКЛ (П.Я.Константинов)',
}, {
    ID: 14,
    Region: 'Центральная Якутия',
    PhysicalGeographicalArea: 'Приленское плато',
    Well: '202',
    ObservationPeriod: '1998-2021',
    GeographicalCoordinates: '61.18396, 128.50360',
    Altitude: '219',
    WellDepth: '20',
    STSrange: '-1,3...-3,8',
    GroundTemperature: '-3,0 (15)',
    RockTemperature: '',
    MeasuredDepth: '',
    STSpower: '1,2',
    SoilCompositionSTS: 'Пылеватые суглинки',
    SoilCompositionMMP: 'Пылеватые суглинки, супеси, алевролиты, песчаники (30%)',
    MesoreliefElement: 'Выположенный участок денудационно-аккумулятивной равнины',
    VegetationCover: 'Лиственничный лес брусничный',
    GroundCover: 'Лесная подстилка (5 см)',
    SnowCoverRange: '25-55',
    PermafrostSpecialist: 'ЛКЛ (П.Я.Константинов)',
}, {
    ID: 15,
    Region: 'Центральная Якутия',
    PhysicalGeographicalArea: 'Приленское плато',
    Well: '203',
    ObservationPeriod: '2000-2021',
    GeographicalCoordinates: '62.18356, 129.37479',
    Altitude: '220',
    WellDepth: '20',
    STSrange: '-1,5...-3,6',
    GroundTemperature: '-2,8 (15)',
    RockTemperature: '',
    MeasuredDepth: '',
    STSpower: '1,2',
    SoilCompositionSTS: 'Пылеватые суглинки',
    SoilCompositionMMP: 'Пылеватые суглинки, супеси, алевролиты, песчаники (30%)',
    MesoreliefElement: 'Выположенный участок денудационно-аккумулятивной равнины',
    VegetationCover: 'Лиственничный лес разнотравно-брусничный',
    GroundCover: 'Лесная подстилка (5 см)',
    SnowCoverRange: '25-55',
    PermafrostSpecialist: 'ЛКЛ (П.Я.Константинов)',
}, {
    ID: 16,
    Region: 'Центральная Якутия',
    PhysicalGeographicalArea: 'Приленское плато',
    Well: '204',
    ObservationPeriod: '2000-2021',
    GeographicalCoordinates: '62.18306, 129.36453',
    Altitude: '218',
    WellDepth: '20',
    STSrange: '-1,0...-4,4',
    GroundTemperature: '-2,5 (15)',
    RockTemperature: '',
    MeasuredDepth: '',
    STSpower: '1,4',
    SoilCompositionSTS: 'Пылеватые суглинки',
    SoilCompositionMMP: 'Пылеватые суглинки, супеси, алевролиты, песчаники (30%)',
    MesoreliefElement: 'Выположенный участок денудационно-аккумулятивной равнины',
    VegetationCover: 'Подрост березы на сплошной вырубке 1991 г.',
    GroundCover: 'Лесная подстилка (5 см)',
    SnowCoverRange: '25-55',
    PermafrostSpecialist: 'ЛКЛ (П.Я.Константинов)',
}, {
    ID: 17,
    Region: 'Центральная Якутия',
    PhysicalGeographicalArea: 'Центральноякутская равнина',
    Well: '18-й км',
    ObservationPeriod: '2009-2016',
    GeographicalCoordinates: '61.51031, 130.08045',
    Altitude: '143',
    WellDepth: '20',
    STSrange: '',
    GroundTemperature: '-2,8 (15)',
    RockTemperature: '',
    MeasuredDepth: '',
    STSpower: '1,4',
    SoilCompositionSTS: 'Пылеватые суглинки, супеси, пески',
    SoilCompositionMMP: 'Супеси, пески (15%)',
    MesoreliefElement: 'Привершинная поверхность пологого увала',
    VegetationCover: 'Молодой сосново-лиственничный лес брусничный',
    GroundCover: 'Лесная подстилка (3 см)',
    SnowCoverRange: '25-55',
    PermafrostSpecialist: 'ЛКЛ (П.Я.Константинов)',
}, {
    ID: 18,
    Region: 'Центральная Якутия',
    PhysicalGeographicalArea: 'Центральноякутская равнина',
    Well: '12-й км',
    ObservationPeriod: '2002-2021',
    GeographicalCoordinates: '61.52532, 130.03172',
    Altitude: '132',
    WellDepth: '10',
    STSrange: '-0,5...-2,8',
    GroundTemperature: '-2,0 (10)',
    RockTemperature: '',
    MeasuredDepth: '',
    STSpower: '1,9',
    SoilCompositionSTS: 'Пески',
    SoilCompositionMMP: 'Пески (10%)',
    MesoreliefElement: 'Привершинная поверхность песчаной гряды',
    VegetationCover: 'Сосновый лес толокнянковый',
    GroundCover: 'Лесная подстилка (1 см)',
    SnowCoverRange: '25-45',
    PermafrostSpecialist: 'ЛКЛ (П.Я.Константинов)',
}, {
    ID: 19,
    Region: 'Центральная Якутия',
    PhysicalGeographicalArea: 'Центральноякутская равнина',
    Well: '4-н',
    ObservationPeriod: '2015-2021',
    GeographicalCoordinates: '61.45351, 130.28276',
    Altitude: '230',
    WellDepth: '20',
    STSrange: '-0,5...-0,7',
    GroundTemperature: '-1,4 (15)',
    RockTemperature: '',
    MeasuredDepth: '',
    STSpower: '1,3',
    SoilCompositionSTS: 'Пылеватые суглинки',
    SoilCompositionMMP: 'Пылеватые суглинки, супеси, пески (60%)',
    MesoreliefElement: 'Межаласная поверхность Абалахской террасы р.Лены',
    VegetationCover: 'Березово-лиственничный лес разнотравно-брусничный',
    GroundCover: 'Лесная подстилка (3 см)',
    SnowCoverRange: '25-55',
    PermafrostSpecialist: 'ЛКЛ (П.Я.Константинов)',
}, {
    ID: 20,
    Region: 'Центральная Якутия',
    PhysicalGeographicalArea: 'Приленское плато',
    Well: '1',
    ObservationPeriod: '1996-2021',
    GeographicalCoordinates: '62.15178, 129.37030',
    Altitude: '216',
    WellDepth: '7',
    STSrange: '-1,2...-3,4',
    GroundTemperature: '',
    RockTemperature: '',
    MeasuredDepth: '',
    STSpower: '1,5',
    SoilCompositionSTS: 'Супеси, пески',
    SoilCompositionMMP: 'Супеси, пески (15%)',
    MesoreliefElement: 'Верхняя часть пологого склона',
    VegetationCover: 'Лиственничный лес разнотравно-брусничный',
    GroundCover: 'Лесная подстилка (5 см)',
    SnowCoverRange: '25-50',
    PermafrostSpecialist: 'ЛКЛ (П.Я.Константинов)',
}, {
    ID: 21,
    Region: 'Центральная Якутия',
    PhysicalGeographicalArea: 'Приленское плато',
    Well: '2',
    ObservationPeriod: '1996-2021',
    GeographicalCoordinates: '62.15120, 129.37010',
    Altitude: '219',
    WellDepth: '7',
    STSrange: '-0,6...-2,3',
    GroundTemperature: '',
    RockTemperature: '',
    MeasuredDepth: '',
    STSpower: '1,9',
    SoilCompositionSTS: 'Супеси, пески',
    SoilCompositionMMP: 'Супеси, пески (15%)',
    MesoreliefElement: 'Верхняя часть пологого склона',
    VegetationCover: 'Лиственнично-березовый лес разнотравно-брусничный',
    GroundCover: 'Лесная подстилка (3 см)',
    SnowCoverRange: '25-50',
    PermafrostSpecialist: 'ЛКЛ (П.Я.Константинов)',
}, {
    ID: 22,
    Region: 'Центральная Якутия',
    PhysicalGeographicalArea: 'Приленское плато',
    Well: '11',
    ObservationPeriod: '1996-2021',
    GeographicalCoordinates: '62.15179, 129.37131',
    Altitude: '222',
    WellDepth: '7',
    STSrange: '-0,6...-2,7',
    GroundTemperature: '',
    RockTemperature: '',
    MeasuredDepth: '',
    STSpower: '2,1',
    SoilCompositionSTS: 'Пески',
    SoilCompositionMMP: 'Пески (7%)',
    MesoreliefElement: 'Привершинная поверхность песчаной гряды',
    VegetationCover: 'Сосновый лес толокнянково-лишайниковый',
    GroundCover: 'Сосновый опад, лишайники (1-2 см)',
    SnowCoverRange: '25-45',
    PermafrostSpecialist: 'ЛКЛ (П.Я.Константинов)',
}, {
    ID: 23,
    Region: 'Центральная Якутия',
    PhysicalGeographicalArea: 'Приленское плато',
    Well: 'J1',
    ObservationPeriod: '2012-2021',
    GeographicalCoordinates: '62.34432, 125.02026',
    Altitude: '250',
    WellDepth: '4',
    STSrange: '-1,3...-3,2',
    GroundTemperature: '',
    RockTemperature: '',
    MeasuredDepth: '',
    STSpower: '1,3',
    SoilCompositionSTS: 'Супеси, суглинки',
    SoilCompositionMMP: 'Супеси, пески (20%)',
    MesoreliefElement: 'Привершинная поверхность пологого увала',
    VegetationCover: 'Березово-лиственничный лес брусничный',
    GroundCover: 'Лесная подстилка (5 см)',
    SnowCoverRange: '30-55',
    PermafrostSpecialist: 'ЛКЛ (П.Я.Константинов)',
}, {
    ID: 24,
    Region: 'Центральная Якутия',
    PhysicalGeographicalArea: 'Приленское плато',
    Well: 'J3',
    ObservationPeriod: '2012-2021',
    GeographicalCoordinates: '63.22236, 123.27527',
    Altitude: '175',
    WellDepth: '4',
    STSrange: '1,0...1,8',
    GroundTemperature: '',
    RockTemperature: '',
    MeasuredDepth: '',
    STSpower: '1,5-1,9 (СМС)',
    SoilCompositionSTS: 'Пески',
    SoilCompositionMMP: 'Пески талые',
    MesoreliefElement: 'Привершинная поверхность пологого увала',
    VegetationCover: 'Сосновый лес мертвопокровный',
    GroundCover: 'Сосновый опад (1 см)',
    SnowCoverRange: '30-55',
    PermafrostSpecialist: 'ЛКЛ (П.Я.Константинов)',
}, {
    ID: 25,
    Region: 'Центральная Якутия',
    PhysicalGeographicalArea: 'Центральноякутская равнина',
    Well: 'J2',
    ObservationPeriod: '2012-2021',
    GeographicalCoordinates: '63.38169, 119.46376',
    Altitude: '129',
    WellDepth: '4',
    STSrange: '-1,3...-2,6',
    GroundTemperature: '',
    RockTemperature: '',
    MeasuredDepth: '',
    STSpower: '1,3',
    SoilCompositionSTS: 'Супеси, пески',
    SoilCompositionMMP: 'Супеси, пески (10%)',
    MesoreliefElement: 'Привершинная поверхность пологого увала',
    VegetationCover: 'Березово-лиственничный лес брусничный<',
    GroundCover: 'Лесная подстилка (5 см)',
    SnowCoverRange: '30-55',
    PermafrostSpecialist: 'ЛКЛ (П.Я.Константинов)',
}, {
    ID: 26,
    Region: 'Центральная Якутия',
    PhysicalGeographicalArea: 'Центральноякутская равнина',
    Well: 'J4',
    ObservationPeriod: '2012-2021',
    GeographicalCoordinates: '62.12423, 116.34178',
    Altitude: '210',
    WellDepth: '4',
    STSrange: '-0,3...-1,2',
    GroundTemperature: '',
    RockTemperature: '',
    MeasuredDepth: '',
    STSpower: '1,4',
    SoilCompositionSTS: 'Супеси, пески',
    SoilCompositionMMP: 'Супеси, пески (15%)',
    MesoreliefElement: 'Привершинная поверхность пологого увала',
    VegetationCover: 'Березово-лиственничный лес кустарничково-моховый<',
    GroundCover: 'Зеленые мхи (5 см)',
    SnowCoverRange: '30-60',
    PermafrostSpecialist: 'ЛКЛ (П.Я.Константинов)',
}, {
    ID: 27,
    Region: 'Западная Якутия',
    PhysicalGeographicalArea: 'Вилюйское плато',
    Well: 'J5',
    ObservationPeriod: '2012-2021',
    GeographicalCoordinates: '63.26352, 112.29151',
    Altitude: '285',
    WellDepth: '4',
    STSrange: '-0,1...-1,0',
    GroundTemperature: '',
    RockTemperature: '',
    MeasuredDepth: '',
    STSpower: '1,6',
    SoilCompositionSTS: 'Супеси, пески',
    SoilCompositionMMP: 'Супеси, пески (15%)',
    MesoreliefElement: 'Надпойменная терраса',
    VegetationCover: 'Редкостойный березово-лиственничный лес кустарничково-лишайниковый',
    GroundCover: 'Лишайники (3 см)',
    SnowCoverRange: '35-60',
    PermafrostSpecialist: 'ЛКЛ (П.Я.Константинов)',
}, {
    ID: 28,
    Region: 'Восточная Якутия',
    PhysicalGeographicalArea: 'Хребет Сунтар-Хаята',
    Well: 'нет',
    ObservationPeriod: '2010-2021',
    GeographicalCoordinates: '63.03443, 138.49286',
    Altitude: '1103',
    WellDepth: '190 (мониторинг на глубинах 1, 5, 10 и 15 м)',
    STSrange: '-4,1...-5,6',
    GroundTemperature: '-4,3 (15)',
    RockTemperature: '-4.04 (20 м), -3.84 (40 м), -3.53 (60 м), -3.16 (80 м), -2.70 (100 м)',
    MeasuredDepth: '190',
    STSpower: 'около 2,3м',
    SoilCompositionSTS: 'Глинистый сланец, песчаники, алевролиты',
    SoilCompositionMMP: 'менее 5%',
    MesoreliefElement: 'Выположенный склон северо-западной экспозиции',
    VegetationCover: 'Кедровый стланик, кусты ивы, карликовая берёзы, редкая невысокая лиственница, разнотравие',
    GroundCover: 'Разнотравье, поверхность не восстановилась после бурение. Зона развития ягеля',
    SnowCoverRange: 'По метеостанции Восточная 35-55 см.',
    PermafrostSpecialist: 'ЛГК (Р.Г. Сысолятин)',
}, {
    ID: 29,
    Region: 'Восточная Якутия',
    PhysicalGeographicalArea: 'Хребет Сунтар-Хаята',
    Well: 'нет',
    ObservationPeriod: '2012-2021',
    GeographicalCoordinates: '63.07027, 139.00137',
    Altitude: '916',
    WellDepth: '4',
    STSrange: '-2,8...-5,1',
    GroundTemperature: '-3,7 (5)',
    RockTemperature: 'н/д',
    MeasuredDepth: 'н/д',
    STSpower: '2,6',
    SoilCompositionSTS: 'Песчаник, алевролиты, глинистый сланец',
    SoilCompositionMMP: 'До 10%',
    MesoreliefElement: 'Боковая морена',
    VegetationCover: 'Редкая лиственница до 8-10 м, брусничник',
    GroundCover: 'Ягель до 10 см',
    SnowCoverRange: 'По метеостанции Восточная 35-55 см.',
    PermafrostSpecialist: 'ЛГК (Р.Г. Сысолятин)',
}, {
    ID: 30,
    Region: 'Восточная Якутия',
    PhysicalGeographicalArea: 'Хребет Сунтар-Хаята',
    Well: 'нет',
    ObservationPeriod: '2012-2021',
    GeographicalCoordinates: '63.07015, 138.08464',
    Altitude: '981',
    WellDepth: '4',
    STSrange: '-1,7...-4,1',
    GroundTemperature: '-4,6 (4)',
    RockTemperature: 'н/д',
    MeasuredDepth: 'н/д',
    STSpower: '0,9-1,1',
    SoilCompositionSTS: 'Песчаник, алевролиты, глинистый сланец',
    SoilCompositionMMP: 'До 30%',
    MesoreliefElement: 'Коллювиальный склон',
    VegetationCover: 'Редкая лиственница до 8-10 м, брусничник',
    GroundCover: 'Мощный ягельно-моховый покров до 20 см',
    SnowCoverRange: 'По метеостанции Восточная 35-55 см.',
    PermafrostSpecialist: 'ЛГК (Р.Г. Сысолятин)',
}];

export default {
    getOrders() {
        return orders;
    },
};
